### ISSUE TITLE
CURLOPT_FOLLOWLOCATION cannot be activated

### ISSUE THREAD

**Issue by ghost** [Xxplosions/twitchtv-oauth#1]
$access_token = $twitchtv->get_access_token("XXXX");:

ERROR:
Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in /XXXX/auth/twitchtv.php on line 64

The support of my hoster told me, that the safe_mode is deactivated but that they can't change the open_basedir parameter for security reasons. I could only do this on a managed server where I have full access.

Do you know if it is possible to solve this problem inside the PHP code with another methodic approach for people like me that dont have managed servers running? Or do I need to switch to another contract only to use this class? I have my fingers crossed :)

Thank you for your time and the sharing of your work

Mortimer

**Comment by EliasRanz** [comment]
Dammit, just saw this Mortimer I apologize. Sorry I haven't been very active updating this, though I think it's time for me to get back into it and scale it up a little bit and revisit the code. I applied a fix in the following commit https://github.com/Xxplosions/twitchtv-oauth/commit/85b6837e7a62affbea919c6140250462cdade478
