### ISSUE TITLE
authenticated_user

### ISSUE THREAD

**Issue by Streusel** [Xxplosions/twitchtv-oauth#4]
It appears twitch has deprecated the 'error' field on https://github.com/Xxplosions/twitchtv-oauth/blob/master/twitchtv.php#L98
The correct way to check if something worked or not is to check the ['token']['valid'] field now, the response will be bool(true) or bool(false).

**Comment by Xxplosions** [comment]
#3 looks like it's related.

**Comment by EliasRanz** [comment]
Looking at this a little further it appears that they haven't changed it. If you check the json object on their [Readme.md](https://github.com/justintv/Twitch-API/blob/ffe3ac08bb3ef43ee8d890b3b2a528ff7b619809/README.md#errors) you will see that "error" is at the base of the object so you shouldn't need to hit `['token']` if you have an example of the documentation that states there is an issue then let me know and I'll adjust it accordingly. Sorry about the lengthy delay in response, haven't had the motivation to look back at it.

**Comment by EliasRanz** [comment]
Just checked the [base url on the api](https://api.twitch.tv/kraken/) and it looks like you're correct.
