### ISSUE TITLE
Error converting to string

### ISSUE THREAD

**Issue by Streusel** [Xxplosions/twitchtv-oauth#5]
https://github.com/Xxplosions/twitchtv-oauth/blob/master/twitchtv.php#L74
And other instances of where `$fields` is being used needs to be wrapped in `http_build_query()` such that we have this following result:
`curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($fields));
`

**Comment by EliasRanz** [comment]
Updated all the references should be all set let me know if there are any other bugs and I'll be sure to work them out. Sorry about such a long delay. If you come across anything and want to merge changes into the actual project go for it.
