### ISSUE TITLE
Version 5

### ISSUE THREAD

**Issue by CreativeCodeCat** [Xxplosions/twitchtv-oauth#7]
will this be updated to version 5 of the api???

**Comment by CreativeCodeCat** [comment]
[Forum Link](https://discuss.dev.twitch.tv/t/twitch-api-version-update-discussion-faq/8132/68) 
[Blog Link](https://discuss.dev.twitch.tv/t/twitch-api-version-update-discussion-faq/8132/68)

**Comment by EliasRanz** [comment]
Fixed via #8
